function run_all_figures()
%RUN_ALL_FIGURES 顺序生成问题一的全部 12 张图。
    jobs = {@plot_01_main_experiment_comparison, ...
            @plot_02_bp_structural_comparison, ...
            @plot_03_sample_relative_errors, ...
            @plot_04_ice_fraction_saturation, ...
            @plot_05_voltage_loss_decomposition, ...
            @plot_06_bp_water_energy_balances, ...
            @plot_07_main_spacetime_fields, ...
            @plot_08_bp_spacetime_fields, ...
            @plot_09_freezing_identifiability, ...
            @plot_10_phase_coefficient_sensitivity, ...
            @plot_11_phase_cumulative_amounts, ...
            @plot_12_near_optimal_ice_scenarios};
    for k = 1:numel(jobs)
        fprintf('正在生成 %02d/12 ...\n', k);
        fig = jobs{k}();
        close(fig);
    end
    fprintf('全部 MATLAB 图已生成。\n');
end
